sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jeffet/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true jeffet/docker-react -f dockerfile.dev npm run test
